FROM node:18-alpine as builder
ARG PNPM_VERSION=8.1.1

RUN npm --global install pnpm@${PNPM_VERSION}
RUN npm install http-server -g
RUN apk add --no-cache git

WORKDIR /app

COPY .npmrc .npmignore package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY ./site/package.json ./site/package.json
COPY ./plugin/package.json ./plugin/package.json
COPY ./icon/package.json ./icon/package.json

COPY . .

# expose the host and port 3000 to the server
ENV HOST 0.0.0.0
EXPOSE 3000
EXPOSE 8080
EXPOSE 24678

# run the build project with node
ENTRYPOINT ["sh", "/app/site/docker/script/entrypoint.sh"]
