version: '3'
services:
  web:
    build:
      dockerfile: ./site/docker/Dockerfile.prod
      context: ../../.
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: icons
      MONGO_INITDB_USERNAME: icon
      MONGO_INITDB_PASSWORD: 123456
volumes:
  mongodb-data:
  redis-data:
